### ISSUE TITLE
Compatibility issue with All in One SEO Pack

### ISSUE THREAD

**Issue by arnaudbroes** [10up/simple-page-ordering#20] opened 2018-04-15 17:41 UTC
All in One SEO Pack users are no longer able to edit their pages' titles, descriptions and keywords on the Pages screen when this plugin is activated because the text area becomes non-clickable.

![image](https://user-images.githubusercontent.com/18156697/38781435-bc633abe-40e4-11e8-94ad-b6c6cb2f4884.png)

**Comment by oscarssanchez** [comment] 2018-04-20 18:28
Hi @arnaudbroes . This two solutions have worked for me so far: 

Either: 

- Add `	cancel:	'input, textarea, button, select, option, .inline-edit-row',` in line 71 of the js file.
- Knock out line 71.

Hope this works for you too

**Comment by helen** [comment] 2018-05-01 18:12
@arnaudbroes Thanks for the report! I'm going to close this as a duplicate of #13 and look to get this fixed in a release soon.

**Closed by helen** 2018-05-01 18:12 UTC
Labels: closed:duplicate

**Comment by arnaudbroes** [comment] 2018-05-03 19:36
Cool, thank you!
