### ISSUE TITLE
Git repository should not be included in the released plugin.

### ISSUE THREAD

**Issue by tekapo** [10up/simple-page-ordering#178] opened 2023-11-07 05:48 UTC
### Describe the bug

Thank you for the plugin!

I've found the released plugin, version 2.6.0 includes a git repository located at:
`simple-page-ordering/10up-lib/wp-compat-validation-tool/.git`
 

### Steps to Reproduce

1. Go to https://wordpress.org/plugins/simple-page-ordering/
2. Hit the Download button.
3. Open the zip file.
4. You will find the Git repository located at:
`simple-page-ordering/10up-lib/wp-compat-validation-tool/.git`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jeroenlammerts** [comment] 2023-11-07 12:30
Duplicate of #169

**Comment by jeffpaul** [comment] 2023-11-07 15:11
Closing in favor of #169.

**Closed as not planned by jeffpaul** 2023-11-07 15:11 UTC
Labels: type:bug
